### PR TITLE
macOS build setup

### PR DESCRIPTION
**Pull request by Okeanos**
In reference to my original pull request (see https://github.com/NXPmicro/mfgtools/pull/206 ) I had another go at improving the macOS build setup.

- I minimised the actual CMake changes to a single build variable
- I added a newer version of macOS to the Travis CI Job and changed some of the existing toolchain in there
  - the git depth of 300 does not appear to actually work according to the Travis [CI documentation](https://docs.travis-ci.com/user/customizing-the-build/#git-clone-depth): "Travis CI can clone repositories to a maximum depth of 50 commits […]"
  - `brewfile` instructions appear to be unnecessary because this project doesn't use a Brewfile
  - installing `pkg-config` via brew appears to be easier from my perspective compared to exporting a hard coded location
- I updated the readme to use code syntax where actual code is supposed to be executed, e.g. the build instructions, and stripped trailing whitespace
- Flashing something with the uuu tool build with these instructions has actually been tested now, it works (on my machine) 🎉 

Changing the very specific location of the OpenSSL dependency to be less version specific does not appear to be feasible at this time. We could symlink it for Travis via the matrix for macOS specifically but this wouldn't help local builds at all.

### CODE REVIEW

**Comment by nxpfrankli** [comment]
Did you test uuu at mac OS?  I remember there are HID driver unload problem at mac os. 

Please rebase and merge to one commit for cmake file change.

**Comment by Okeanos** [comment]
I will give you more in depth testing results on macOS next week and also update the pull request as requested.

**Comment by Okeanos** [comment]
So, the good news is that a colleague and I could **successfully** verify this week that using the build instructions from this PR the uuu tool can be used to flash hardware under **macOS Catalina (10.15.x)**. I make a new pull request shortly that includes the minimal set of changes as per your request :).

**Comment by MarsPlanet** [comment]
I am getting this error when i try to build for mac os following the steps


CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at libuuu/CMakeLists.txt:58:
  Syntax Warning in cmake code at column 159

  Argument not separated from preceding token by whitespace.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  Could NOT find BZip2 (missing: BZIP2_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.18.2/share/cmake/Modules/FindBZip2.cmake:63 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  libuuu/CMakeLists.txt:6 (find_package)


-- Configuring incomplete, errors occurred!

**Comment by Okeanos** [comment]
As stated in the notes `bzip2` should be supplied via XCode. Do you have that installed (and if so as full or partial installation)?

**Pull request closed without merging**
